# Generated by Django 2.2.3 on 2019-07-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190702_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
