# Generated by Django 2.2.3 on 2019-07-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190702_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
